// Browser-only design preview. Never bundled state or real integration receipts.
if (location.hostname === '127.0.0.1' || location.hostname === 'localhost') {
  window.ORACLE_PREVIEW = true;
  const collections = [['ads','Ads','megaphone'],['code','Code','code'],['contents','Contents','note'],['customer-finder','Customer Finder','search'],['marketing','Marketing','chart'],['personal-branding','Personal Branding','person']].map(([id,name,icon])=>({id,name,icon}));
  const names={ads:['ads-audit','ads-google','ads-meta','ads-creative'],code:['branch-pr','chained-pr','cognitive-doc-design','comment-writer'],contents:[], 'customer-finder':['first-customer-finder'],marketing:['ab-testing','ad-creative','ai-seo','analytics','aso'],'personal-branding':[]};
  const files=['INBOX/oracle/Identidade.md','INBOX/oracle-history/conversations/Conversa de exemplo.md','INBOX/oracle-memory/people/Pessoa de exemplo.md','INBOX/oracle-memory/projects/Projeto de exemplo.md','INBOX/oracle-memory/signals/Sinal de exemplo.md','PROJETOS/Meu primeiro projeto.md','WIKI/Conexões e fontes.md','AREAS/Conhecimento.md'];
  files.push('AREAS/pessoal/Perfil.md','AREAS/profissional/Perfil.md');
  for(const [id,skills] of Object.entries(names))for(const skill of skills)files.push(`SISTEMA/skills/${id}/${skill}/SKILL.md`);
  const dirs=new Set();files.forEach(path=>{const parts=path.split('/');parts.pop();for(let i=1;i<=parts.length;i++)dirs.add(parts.slice(0,i).join('/'))});
  const entries=[...dirs].map(path=>({path,name:path.split('/').at(-1),directory:true,source:'Demonstração'})).concat(files.map(path=>({path,name:path.split('/').at(-1),directory:false,source:'Demonstração',size:128})));
  const snapshot={config:{vault:'Vault de demonstração · nenhuma pasta pessoal acessada',layout:JSON.parse(localStorage.getItem('oracle-preview-layout')||'null')},entries,collections,events:[],projects:[],engine:'Demonstração'};
  const profileDemo={
    personal:'# Perfil de demonstração\n\nUma pessoa que valoriza autonomia, tempo com a família e espaço para aprender. Busca uma rotina equilibrada, com atenção ao bem-estar e aos projetos que fazem sentido para ela.\n\n## Rotina e interesses\n\nMantém momentos reservados para leitura e atividades ao ar livre, além de encontros com familiares e amigos.\n\nGosta de aprender coisas novas e registrar ideias para retomar com calma.\n\n## Planos e prioridades\n\nQuer organizar melhor a semana, proteger o tempo de descanso e concluir um projeto pessoal de cada vez.',
    professional:'# Perfil profissional de demonstração\n\nResponsável pelo Estúdio Horizonte, uma empresa fictícia de serviços digitais para pequenos negócios. Sua atuação reúne estratégia, relacionamento com clientes e acompanhamento das entregas.\n\n## Atuação e empresa\n\nA empresa ajuda seus clientes a organizar a presença digital e melhorar a experiência de quem usa seus serviços.\n\n## Projetos e responsabilidades\n\nAcompanha a reformulação de um site, orienta parceiros e revisa as prioridades de cada entrega.\n\n## Direção profissional\n\nO próximo objetivo é consolidar uma oferta principal e estabelecer uma rotina previsível de atendimento.',
    memory:'# Contexto preservado de demonstração\n\nAs conversas disponíveis registram preferências de comunicação, decisões sobre projetos e assuntos que precisam ser retomados. Esse contexto ajuda a manter continuidade entre sessões.\n\n## Preferências e decisões\n\nPrefere explicações diretas, exemplos concretos e um próximo passo claro.\n\nDecidiu revisar o escopo do projeto antes de iniciar novas entregas.\n\n## Assuntos em andamento\n\nFalta organizar os materiais de referência e preparar a próxima revisão do projeto.'
  };
  function previewDocument(path){
    if(path==='AREAS/pessoal/Perfil.md')return profileDemo.personal;
    if(path==='AREAS/profissional/Perfil.md')return profileDemo.professional;
    if(path==='PROJETOS/Meu primeiro projeto.md')return '# Projeto de demonstração\n\n## Projetos e responsabilidades\n\nEstá organizando as etapas de uma reformulação de site, desde a revisão dos conteúdos até a apresentação para o cliente.';
    const slug=String(path||'').split('/').at(-1).replace(/\.md$/i,'');
    if(path.endsWith('SKILL.md'))return `---\nname: ${path.split('/').at(-2)}\ndescription: Exemplo para testar a navegação visual.\n---\n\n# Preview do Oracle\n\nEste texto é uma fixture de interface, não o conteúdo da skill original.\n\nNo aplicativo macOS, este painel lê a fonte autorizada e permite editar o documento original com recuperação e detecção de conflitos.`;
    return '# Documento de demonstração\n\nO preview permite experimentar a navegação. Acesso real ao vault, autenticação e integrações ficam no aplicativo macOS.';
  }
  window.webkit={messageHandlers:{oracle:{postMessage({id,method,params:p}){setTimeout(()=>{let value=null,error=null;switch(method){case 'boot':value={locked:false};break;case 'snapshot':value=snapshot;break;case 'saveLayout':localStorage.setItem('oracle-preview-layout',JSON.stringify(p.layout));snapshot.config.layout=p.layout;value=true;break;case 'events':case 'conversations':case 'instructions':value=[];break;case 'read':value={path:'DEMONSTRAÇÃO/'+p.path,hash:'preview-sem-hash-real',text:previewDocument(p.path)};break;case 'gbrainRead':if(p.operation==='status')value={engine:'Fixture local',version:'teste',sources:[{id:'slow-fixture',name:'Codex · ChatGPT (demonstração)'},{id:'fast-fixture',name:'Claude Code (demonstração)'}]};else if(['list','search'].includes(p.operation))value=[{slug:'fixture',title:'Documento de '+p.source,source_id:p.source}];else if(p.operation==='get')value={title:'Documento de '+p.source,slug:'fixture',source_id:p.source,compiled_truth:profileDemo.memory};else value=[];break;case 'copy':navigator.clipboard?.writeText(p.text);value=true;break;case 'unlock':value=true;break;case 'revoke':value=true;break;default:error='Este recurso usa o aplicativo macOS. O navegador está em demonstração visual.'}window.oracleReply(id,error?{error}:{value})},method==='gbrainRead'&&p.operation!=='status'?(p.source==='slow-fixture'?1200:50):40)}}}};
}
